### ISSUE TITLE
surf[-alggeo] Debian packaging

### ISSUE THREAD

**Issue by jgmbenoit** [remyoudompheng/surf-1#1]
Bonjour Remy,
I am currently packaging surf on behalf of the Debian Science Team [1,2]:
my motivation is to fullfill singular [3] dependencies, the real target being sage [4].
I was directed to your GitHub repository by Marc Mezzarobba [1].

My raw materail, so to speak, is the upstream tar ball available at SourceForge [2],
version 1.0.6. I am at the preliminary stage of the packaging. I can build without
difficulties the CLI surf, but I fail to build the GUI: the issue is that the GUI is built upon GTK1
which is no more distributed by Debian, and that the port from GTK1 to GTK2 is not obvious.
Of course the main part is the CLI. But I would like to get an GUI: so I trying to build your GTK2 version: I can build it by importing the gtk2gui into the upstream source: but it looks as a Work In Progress, is it correct ? Of course I could check against your github code, but unfortunatlelly I cannot build it. Otherwise, do you know where I could find a working GUI for surf.
Note that I am not familiar with GTK stuff, and not familliar with C++ (but I am a proficient C coder and a Debian contributor with some experience :-))

Thanks in advance,
bon courage,
Jerome

[1] https://qa.debian.org/developer.php?login=calculus%40rezozer.net
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777132
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764475
[4] https://wiki.debian.org/DebianScience/Sage

**Comment by remyoudompheng** [comment]
Bonjour Jérôme,
I am not aware of a working GUI using a modern library to use surf. I have not had interest in the subject in the past years so am unfortunately unable to assist.

In this repository no actual code but mere stubs from a failed attempt were written, at times where I encountered the same issues as you. I should not leave it public to avoid misguiding. 

Rémy.

**Comment by jgmbenoit** [comment]
Bonjour, thanks for your reply. You confirm what I suspected. Bon courage, Jerome
